name: Release
on: push

env:
  GO_VERSION: '1.14'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  go-build:
    runs-on: ubuntu-18.04
    name: Build ${{ matrix.goos }}-${{ matrix.goarch }}
    strategy:
      matrix:
        goos: [ 'linux', 'darwin', 'windows' ]
        goarch: [ 'amd64' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2-beta
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: CGO_ENABLED=0 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o documentation-${{ matrix.goos }}-${{ matrix.goarch }} main.go
      - uses: actions/upload-artifact@v1
        with:
          name: documentation-${{ matrix.goos }}-${{ matrix.goarch }}
          path: documentation-${{ matrix.goos }}-${{ matrix.goarch }}
  release:
    runs-on: ubuntu-18.04
    name: Release Documentation
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: .artifacts
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          dry_run: false
          semantic_version: 17.0.4
          extra_plugins: |
            @semantic-release/exec@5.0.0